pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'node-frontend'
        DOCKER_TAG = 'latest'
        REGISTRY_CREDENTIAL = 'DOCKER_CREDENTIALS'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps{
                script{
                    withCredentials([string(credentialsId: 'DOCKER_REGISTRY', variable: 'DOCKER_REGISTRY')]) { //set SECRET with the credential content
                        app = docker.build "$DOCKER_REGISTRY/" + DOCKER_IMAGE_NAME + ":$DOCKER_TAG"
                    }
                }
            }
        }   

        stage('Push Docker Image') {
            steps{
                script{
                    docker.withRegistry('', 'DOCKER_CREDENTIALS'){
                        app.push()
                    }
                }
            }
        }
    }
}
